# 2025.09.24 Numpy

In [3]:
import numpy as np

In [4]:
np.__version__

'2.3.3'

In [4]:
L = range(1000)
%timeit L2 = [i **2 for i in L] #timeit은 시간 나타내는 것

27.4 μs ± 82.6 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [6]:
arr = np.arange(1000)
%timeit arr2 = arr**2

685 ns ± 27.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
alist = [1, 2, 3, 4, 5, 6]

In [8]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [9]:
blist = [1, 2, None, 4, 5]

In [ ]:
ar1 = np.array(alist) #배열로 변경(쉼표 없어진 걸 확인할 수 있음)
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
ar1.dtype #64의 의미는 메모리 용량이라 생각하면 됨

dtype('int64')

In [12]:
ar2 = np.array([1.1, 2.2, 3.3])

In [14]:
print(ar2)

[1.1 2.2 3.3]


In [15]:
ar2.dtype

dtype('float64')

In [ ]:
list_dat = [1, 2. , 3] # 하나가 실수이면 모두 실수로 바뀜

ar3 = np.array(list_dat)

print(ar3)
print(ar3.dtype)

[1. 2. 3.]
float64


In [ ]:
list_dat2 = [1, 2. , 3] 

ar33 = np.array(list_dat2, dtype="int") # 바꾸고 싶은 자료형으로 바꿀 수 있음

print(ar33)
print(ar33.dtype)

[1 2 3]
int64


In [ ]:
np.array([1,2, np.nan,4]) # .nan과 None은 비슷(데이터가 없다)

array([ 1.,  2., nan,  4.])

In [ ]:
arr1 = np.array([1,2,3,4]) # 벡터로 받아들임 

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [ ]:
arr2 = np.array([[1,2,3,4]]) #2차원으로 받아들임

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]]
2
(1, 4)


In [8]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [ ]:
arr3 = arr2.reshape(-1, 3) # -1은 행 내가 계산안하고 니가 해라는 의미, 3은 열을 3으로 해달라는 거

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [ ]:
arr3 = arr2.reshape(2, -1, 3) # 2는 3차원으로 만들어줌(뎁스는 3차원으로 가는 길이)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [ ]:
arr3 = arr2.reshape(2, -1, -1) # -1은 하나만 가능 error는 일부러 남겨둠 예시를 위해

print(arr3)
print(arr3.ndim)
print(arr3.shape)

ValueError: can only specify one unknown dimension

In [13]:
alist = np.array([1, 2, 3, 4, 5])
blist = np.array([6,7,8,9,10])

In [14]:
print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
aalist = np.array([1,2,3]) # shape이 같지 않으면 에러가 남(예시 남겨둠)
bblist = np.array([4,5])
print(aalist + bblist)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
aaalist = np.array([1,np.nan]) # nan을 더하면 그냥 nan값이 나옴
bbblist = np.array([3,4])
print(aaalist + bbblist)

[ 4. nan]


In [ ]:
print(alist + 2) #일괄적으로 요소들의 연산 가능
print(alist - 2)
print(alist * 2)
print(alist / 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [25]:
a = np.array([1,2,3])
b = np.array([10,20,30])
a == 2

array([False,  True, False])

In [ ]:
(a == 2) and ( b>10 ) # 벡터 이상의 비교할 때는 &로 해줘야 됨(예시로 남김)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [28]:
alist = [[0,1,2],[3,4,5]]
print(alist[0][0], alist[0][1], alist[1][2])

0 1 5


In [47]:
blist = np.array([[0,1,2],[3,4,5]])
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
print(blist[0,0], blist[0,1], blist[1,2])

0 1 5


In [46]:
alist = [[0,1,2],
         [3,4,5]]
print(alist[0][0:2])
print(alist[1][0:3])
[alist[0][1], alist[1][1]]

[0, 1]
[3, 4, 5]


[1, 4]

In [63]:
print(blist[0,:2])
print(blist[1,:])
print(blist[:,1])
print(blist[[0,1],[1,1]])

[0 1]
[3 4 5]
[1 4]
[1 4]


In [95]:
a = np.array([[0,1,2,3],[4,5,6,7],[9,10,11,12]])
print(a)
#print(a[0,:3]) #[start(포함<=), end(미만<)]
#print(a[:,1])
#print(a[1,1:])
#print(a[0:2,0:2]) #행, 열
print(a[1:,1:])
print(a[0:2,2:4])
print(a[:2,:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 9 10 11 12]]
[[ 5  6  7]
 [10 11 12]]
[[2 3]
 [6 7]]
[[0 1]
 [4 5]]


In [ ]:
aa = np.array([0,1,2,3,4,5,6,7,8,9]) #fancy 불리언 방식
idx = np.array([True, False, True, False, True, False, True, False,True, False])
aa[idx]

array([0, 2, 4, 6, 8])

In [ ]:
aa = np.array([0,1,2,3,4,5,6,7,8,9]) #불리언 방식은 개수는 맞춰야 함(예시로 에러)
idx = np.array([True, False, True)
aa[idx]

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (1800179016.py, line 2)

In [110]:
aa = np.array([1,2,3,4,5,6,7,8,9])
idx = np.array([0,2,5])
aa[idx]

array([1, 3, 6])

In [104]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print("")
print(b[[0,2]])
print("")
print(b[[0,1,2],[1,2,0]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]

[2 6 7]


In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8]) #fancy
print(arr[arr % 2 == 0])
print(arr[arr % 2 == 1])

[0 2 4 6 8]
[1 3 5 7]


In [127]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print("")
print(a[:,[True,False,False,True]])
print("")
print(a[:,[0,3]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  4]
 [ 5  8]
 [ 9 12]]

[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [124]:
print(a[[2,0,1],:])

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [ ]:
data = np.array([1,4,9,16])
print(np.sqrt(data)) #나눗셈 몫
print(np.exp(data)) #거듭제곱
print(np.sum(data)) #더하기
print(np.mean(data)) #평균
print(np.std(data)) #표준편차

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
30
7.5
5.678908345800274


In [136]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,29])
print(x[x % 3 == 0])
print(x[x % 4 == 1])
print(x[(x % 3 == 0)&(x % 4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17 29]
[9]


# Pandas

In [138]:
!pip install pandas

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/11.3 MB 5.9 MB/s eta 0:00:02
   -- ------------------------------------- 0.7/11.3 MB 7.4 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.3 MB 7.4 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.3 MB 7.4 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.3 MB 7.4 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.3 MB 7.4 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.3 MB 7.4 MB/s eta 0:00:02
   ----- ---------------------------------- 1.4/11.3 MB 3.6 MB/s eta 0:00:03
   ------ --------------------------------- 1.9/11.3 MB 4.2 MB/s eta 0:00:03
   -------- ------------------------------- 2.3/11.3 MB 4.7 MB/s eta 0:00:02
   --------- ------------------------------ 2.7/11.3 MB 4.9 MB/s eta 0:00:02
   ----------- ---------------------------- 3.1/11.3 MB 5.3 MB/s eta 0:00:02
   ---


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import pandas as pd

In [12]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [13]:
pd.options.display.float_format = "{:,.0f}".format # 숫자 보이는 방식을 바꾼 것

In [14]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [ ]:
df.info() #데이터가 많을 때 유용(non-null은 빈 칸이 아니라는 거, 데이터분석에서 object는 문자형을 뜻함)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [153]:
df.describe()

나이   키                 재산
count   7   7                  5
mean   34 190  2,300,278,000,120
std    13  36  5,142,800,956,894
min    18 170                600
25%    26 172         50,000,000
50%    32 177        340,000,000
75%    39 184      1,000,000,000
max    58 270 11,500,000,000,000

In [154]:
df.head(3)

이름  나이    직업     국적    키                 재산
0   아이언맨  58   CEO     미국  174 11,500,000,000,000
1     토르  45     신  아스가르드  190                NaN
2  스파이더맨  18  고등학생     미국  177                600

In [157]:
df.tail(4)

이름  나이     직업     국적    키            재산
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
5   캡틴마블  25    파일럿     미국  170   340,000,000
6  블랙위도우  32    스파이    러시아  170    50,000,000

In [158]:
df["국적"] #컬럼명은 적으면 다를 수도 있기 때문에 왠만하면 옆에 뜨는거 선택

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [ ]:
type(df['국적']) #시리즈는 인덱스랑 값만나옴

pandas.core.series.Series

In [ ]:
df['국적'].unique() #반복 없이 나라명 적기

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [ ]:
df['국적'].value_counts() #각 나라에 몇명이 있는지(분포도)

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [ ]:
df['나이'].nlargest() #숫자가 큰 순으로(내림차순)

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [ ]:
df.nlargest(7, '나이') #7은 보고 싶은 순위를 나타냄. 만약 데이터가 많으면 100위까지 보여줘라고 할 수 있음

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000
3   원더우먼  27     공주  데미스키라  178                NaN
5   캡틴마블  25    파일럿     미국  170        340,000,000
2  스파이더맨  18   고등학생     미국  177                600

In [168]:
df.nlargest(7, '키')

이름  나이     직업     국적    키                 재산
4     헐크  33  핵물리학자     미국  270      1,000,000,000
1     토르  45      신  아스가르드  190                NaN
3   원더우먼  27     공주  데미스키라  178                NaN
2  스파이더맨  18   고등학생     미국  177                600
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [ ]:
df['이름'][:5] # 5행 전까지 나오게 함

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: object

In [173]:
df[4:]

이름  나이     직업   국적    키            재산
4     헐크  33  핵물리학자   미국  270 1,000,000,000
5   캡틴마블  25    파일럿   미국  170   340,000,000
6  블랙위도우  32    스파이  러시아  170    50,000,000

In [175]:
df.iloc[1:4] # [행번호, 열번호]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [ ]:
df.iloc[[1,3,6]] # 지정할 때는 : 사용이 안됨

이름  나이   직업     국적    키         재산
1     토르  45    신  아스가르드  190        NaN
3   원더우먼  27   공주  데미스키라  178        NaN
6  블랙위도우  32  스파이    러시아  170 50,000,000

In [179]:
df.iloc[:5, :3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [ ]:
df.loc[2:5]  #[행이름, 열이름] df.loc는 모든 값을 포함해서 가져옴

이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177           600
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
5   캡틴마블  25    파일럿     미국  170   340,000,000

In [187]:
df.loc[:2, ['이름','직업']]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [188]:
df.loc[3:, '국적':'재산']

국적    키            재산
3  데미스키라  178           NaN
4     미국  270 1,000,000,000
5     미국  170   340,000,000
6    러시아  170    50,000,000

In [189]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [215]:
df['나이']>30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [216]:
df[df['나이']>30]

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [202]:
df[(df['나이']<50) & (df['나이']>30)]

이름  나이     직업     국적    키            재산
1     토르  45      신  아스가르드  190           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
6  블랙위도우  32    스파이    러시아  170    50,000,000

In [208]:
df.loc[(df['키']>170) & (df['나이']<50), ['이름','나이','키']]

이름  나이    키
1     토르  45  190
2  스파이더맨  18  177
3   원더우먼  27  178
4     헐크  33  270

In [209]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [220]:
df['전투력'] = 98 # 전투력 열을 추가
df['아이큐'] = 100

In [221]:
df

이름  나이     직업     국적    키                 재산  전투력  아이큐
0   아이언맨  58    CEO     미국  174 11,500,000,000,000   98  100
1     토르  45      신  아스가르드  190                NaN   98  100
2  스파이더맨  18   고등학생     미국  177                600   98  100
3   원더우먼  27     공주  데미스키라  178                NaN   98  100
4     헐크  33  핵물리학자     미국  270      1,000,000,000   98  100
5   캡틴마블  25    파일럿     미국  170        340,000,000   98  100
6  블랙위도우  32    스파이    러시아  170         50,000,000   98  100

In [222]:
df['전투력'] = df['전투력'] - 5
df

이름  나이     직업     국적    키                 재산  전투력  아이큐
0   아이언맨  58    CEO     미국  174 11,500,000,000,000   93  100
1     토르  45      신  아스가르드  190                NaN   93  100
2  스파이더맨  18   고등학생     미국  177                600   93  100
3   원더우먼  27     공주  데미스키라  178                NaN   93  100
4     헐크  33  핵물리학자     미국  270      1,000,000,000   93  100
5   캡틴마블  25    파일럿     미국  170        340,000,000   93  100
6  블랙위도우  32    스파이    러시아  170         50,000,000   93  100

In [ ]:
df.drop(columns=['아이큐']) # 아이큐 열을 임시 삭제(원본 삭제 아님)

이름  나이     직업     국적    키                 재산  전투력
0   아이언맨  58    CEO     미국  174 11,500,000,000,000   93
1     토르  45      신  아스가르드  190                NaN   93
2  스파이더맨  18   고등학생     미국  177                600   93
3   원더우먼  27     공주  데미스키라  178                NaN   93
4     헐크  33  핵물리학자     미국  270      1,000,000,000   93
5   캡틴마블  25    파일럿     미국  170        340,000,000   93
6  블랙위도우  32    스파이    러시아  170         50,000,000   93

In [224]:
df

이름  나이     직업     국적    키                 재산  전투력  아이큐
0   아이언맨  58    CEO     미국  174 11,500,000,000,000   93  100
1     토르  45      신  아스가르드  190                NaN   93  100
2  스파이더맨  18   고등학생     미국  177                600   93  100
3   원더우먼  27     공주  데미스키라  178                NaN   93  100
4     헐크  33  핵물리학자     미국  270      1,000,000,000   93  100
5   캡틴마블  25    파일럿     미국  170        340,000,000   93  100
6  블랙위도우  32    스파이    러시아  170         50,000,000   93  100

In [ ]:
df.drop(columns=['아이큐'], inplace=True) # 아이큐 열 원본 실제 삭제(확정)

In [15]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [20]:
df.info() #결측치 확인 후 결측치 수정하는 방법

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      7 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [ ]:
df['재산'].isnull() # null인 것만 True

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [ ]:
df[df['재산'].isnull()] #null인 것만 불리언 방식으로 보여줌

이름  나이  직업     국적    키  재산  전투력
1    토르  45   신  아스가르드  190 NaN   93
3  원더우먼  27  공주  데미스키라  178 NaN   93

In [ ]:
df.isnull().sum() #null인 통계 보여주는 것

이름     0
나이     0
직업     0
국적     0
키      0
재산     2
전투력    0
dtype: int64

In [ ]:
df.dropna() #결측치를 삭제(임시로 해둠, 확정하려면 inplace=True 해주기)

이름  나이     직업   국적    키                 재산  전투력
0   아이언맨  58    CEO   미국  174 11,500,000,000,000   93
2  스파이더맨  18   고등학생   미국  177                600   93
4     헐크  33  핵물리학자   미국  270      1,000,000,000   93
5   캡틴마블  25    파일럿   미국  170        340,000,000   93
6  블랙위도우  32    스파이  러시아  170         50,000,000   93

In [16]:
df['재산'].fillna(df['재산'].mean()) # nan 부분을 채울 수 있는 함수(임시임). 평균 값으로 재산 입력

0   11,500,000,000,000
1    2,300,278,000,120
2                  600
3    2,300,278,000,120
4        1,000,000,000
5          340,000,000
6           50,000,000
Name: 재산, dtype: float64

In [ ]:
df['재산'].fillna(method = 'ffill') # 앞 또는 뒤 값을 채워넣을 때

C:\Users\EL94\AppData\Local\Temp\ipykernel_3312\2906272721.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['재산'].fillna(method = 'ffill') # nan을 앞 또는 뒤 값을 가져오는 함수


0   11,500,000,000,000
1   11,500,000,000,000
2                  600
3                  600
4        1,000,000,000
5          340,000,000
6           50,000,000
Name: 재산, dtype: float64

In [ ]:
df['재산'] = df['재산'].fillna(df['재산'].mean()) # nan 부분에 값 확정해서 넣는 방법

In [21]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190  2,300,278,000,120
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178  2,300,278,000,120
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [ ]:
def add_cm(height):
    return str(height) + 'cm' # cm 더해주는 함수 적용(파이썬)

def remove_cm(height): # cmcm이 되었을 경우 cm으로 돌려주는 함수(파이썬)
    part = height.replace('cm','') 
    part_float = float(part)
    return str(part_float) + 'cm'

df['키'] = df['키'].apply(remove_cm) #cm 키에 입력
df

이름  나이     직업     국적        키                 재산
0   아이언맨  58    CEO     미국  174.0cm 11,500,000,000,000
1     토르  45      신  아스가르드  190.0cm  2,300,278,000,120
2  스파이더맨  18   고등학생     미국  177.0cm                600
3   원더우먼  27     공주  데미스키라  178.0cm  2,300,278,000,120
4     헐크  33  핵물리학자     미국  270.0cm      1,000,000,000
5   캡틴마블  25    파일럿     미국  170.0cm        340,000,000
6  블랙위도우  32    스파이    러시아  170.0cm         50,000,000

In [ ]:
df.groupby('국적')['나이'].mean() #기준은 국적, 나이의 평균

국적
데미스키라   27
러시아     32
미국      34
아스가르드   45
Name: 나이, dtype: float64